# Generated by Django 5.2.1 on 2025-05-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='perity',
            field=models.IntegerField(default=0),
        ),
    ]
