# Generated by Django 5.2.1 on 2025-05-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0002_task_perity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
