# Generated by Django 5.2.1 on 2025-06-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
